run:
  task: "rcnn"
  mode: "train"

augmentation:
  horizontal_flip: false
  vertical_flip: false
  normalize: true

model:
  architecture: "rcnn"
  input_shape: [1280, 720]
  dropout_rate: 0.5

training:
  batch_size: 1
  epochs: 50
  learning_rate: 0.00001
  shuffle: true

callbacks:
  early_stopping:
    monitor: "val_loss"
    patience: 10
  model_checkpoint:
    filepath: "./checkpoints/best_model.h5"
    save_best_only: true
    monitor: "val_loss"